### ISSUE TITLE
Feature request: Display view upgrade

### ISSUE THREAD

**Issue by MrHumanRebel** [danielnilsson9/bbs-fw#110]
It would be nice to configure the default bottom screen view from these options:
- Current rolling (km)
- Current power (W)
- Motor temperature (C)
- ODO (km)

For example if you want to constantly view the current power instead of the factory default current rolling.
This would be only configurable throught the config tool, and not on the device itself to reduce complexity.

Another thing I might see useful, to be able to modify the time that takes the display to return to the default view when cycling through the menu. For example to change it to 10-15 seconds to have enough time to read the information properly.

Are my ideas feasable?

Thanks in advance!

**Comment by danielnilsson9** [comment]
This firmware is for the controller and only provides data for display. Sounds like you are looking for a display firmware replacement, I'm not aware of any such projects for the bafang display/protocol.

**Comment by MrHumanRebel** [comment]
Sorry, I did not know that this cannot be changed through the motor FW, I just thought it would be a nice thing to have. 
Thanks for letting me/others know!
Have a nice day!
