### ISSUE TITLE
Potential bug: Default PAS setting malfunction

### ISSUE THREAD

**Issue by MrHumanRebel** [danielnilsson9/bbs-fw#113]
I have the default PAS setting set to 0, and when the bike is powered up, it still launches into PAS 1 for some reason.
The config upload was successful.

Current config:
[bbsfw.txt](https://github.com/danielnilsson9/bbs-fw/files/11304555/bbsfw.txt)

Thanks in advance!

**Comment by danielnilsson9** [comment]
Not a bug, please read co figuration guide on wiki https://github.com/danielnilsson9/bbs-fw/wiki/Configuration-Tool

**Comment by MrHumanRebel** [comment]
Ooooo makes sense, thank you!
