### ISSUE TITLE
Editing firmware binary with bbsfwtool

### ISSUE THREAD

**Issue by aalm** [danielnilsson9/bbs-fw#141]
Was wondering if it would be possible to have the configtool rewrite the binary with precomputed lookup tables to
get rid of the floats ? I optimized those out, but the table I put into __code does depend on wheel_size_inch_x10_u16*.

Thinking that this might be acceptable given wheel size does rarely change after initial setup.

**Comment by danielnilsson9** [comment]
Probably possible but I'm not sure why that would be done since it's not currently an issue. There is a lot of computing time left in each loop iteration.
