### ISSUE TITLE
Requête : Walk mode Map on the throttle 

### ISSUE THREAD

**Issue by kb79000** [danielnilsson9/bbs-fw#152]
Hello, would it be possible to map the walk mode with the accelerator for standard operation mode ?
Thx

**Comment by danielnilsson9** [comment]
Same as this issue? https://github.com/danielnilsson9/bbs-fw/issues/112
It's not done yet, haven't been working on this for the last couple of months.

**Comment by kb79000** [comment]
> Identique à ce problème ? #112 Ce n'est pas encore fait, je n'ai pas travaillé dessus ces derniers mois.

Hello Yes it's the same I'm closing
