### ISSUE TITLE
Light Modes

### ISSUE THREAD

**Issue by danielnilsson9** [danielnilsson9/bbs-fw#160]
Add configurable external light modes:

- Default (controlled by display)
- Disabled
- Always On
- Brake Light

**Comment by mgafton** [comment]
Hello Daniel,

First of all, thank you for all your great work and effort, to help the community!
I have installed the firmware on my bbshd, but i am having 3 misbehaviors:

- The speed sensor is intermittently not reading the speed, but if I am gently engaging the throttle, it does read the speed as expected.

- When pressing the lights on button on the  500c display, the motor is making a humming noise and it wants to start, like an walk mode.

If I press the brakes, it stops, then it starts again, it somehow behaves like a walk mode, but much weaker.

- When pressing the Walk mode, it does not display the temperature, as set in the tool.

My MCU is IAP15W4K61S4 and 
I have rolled back to the previous version, also a custom firmware CRR10E4830E105001.1_190413-1, V1..0.4. Hardware version V1.5 used until now, that enables the controller to use 30A, not just 28A.
Does it have to do with the display type, which is 500c?

Thank you once again!
