### ISSUE TITLE
Battery percentage bug

### ISSUE THREAD

**Issue by kb79000** [danielnilsson9/bbs-fw#163]
Hello until today no particular problem but there I have a bug on the battery percentage do you know if it is my battery which is already showing signs of weakness or a potential firmware bug ?
Link video : https://drive.google.com/file/d/1JFOYwya3aSmJ9MoAeftybh92t1_GjRX4/view?usp=drivesdk
Thx

**Comment by danielnilsson9** [comment]
BBS02? Probably same as #114, no solution has been found but workaround for the more severe issues (power cut) was implemented.

**Comment by danielnilsson9** [comment]
Might be something else then, which version are you on?

**Comment by kb79000** [comment]
> Might be something else then, which version are you on?

I'm on version 1.4 I had put a restriction to limit the heating and today it's much cooler than the last time I tested it, I'll put back the original configuration and I hope everything will go back  in order 🤒

**Comment by kb79000** [comment]
I put the original 1.4 back and I have the same problem when I start the maximum power about 1100 watts from the throttle it delivers the power I leave it on for about 30 seconds I cut it and go back on the throttle there  has more than 150 watts or almost nothing, I restart the screen the maximum power is available again and the problem reappears.  There is also sometimes no power coming on the pas mode I am lost .... can error codes like the original bafang firmware also appear on this firmware?  Thank you for your feedback.

**Comment by danielnilsson9** [comment]
Most error codes are implemented but not all I think. Sounds a bit like you are hitting low voltage ramp down but that doesn't entirely fit your description of the problem either. I guess you should try flashing the original firmware

**Comment by kb79000** [comment]
> La plupart des codes d'erreur sont implémentés mais pas tous je pense. On dirait que vous frappez une rampe de basse tension, mais cela ne correspond pas non plus entièrement à votre description du problème. Je suppose que vous devriez essayer de flasher le firmware d'origine

Yes maybe I should go back to the original firmware to see if an error code appears there is a wiki for the return to the original firmware?

**Comment by kb79000** [comment]
I flashed the version available here https://github.com/danielnilsson9/bbs-fw/discussions/94 I test in the evening.

**Comment by kb79000** [comment]
Unfortunately same problem with original bafang firmware and no error code, intermittent power cuts another video : https://youtu.be/qPjzufPbuAI
😢

**Comment by kb79000** [comment]
I'm just giving you a feedback my problem came from a heating point between the battery connector and the support on the negative pole :
[https://rehost.diberie.com/Picture/Get/f/202115](url)
