### ISSUE TITLE
Cant change to 52 v

### ISSUE THREAD

**Issue by ServusDei1** [danielnilsson9/bbs-fw#171]
Hello, after changing in the application to 58.8 v and clicking the save button, I get a message that everything is ok. After clicking the read button, it changes back to 54.6. :/

**Comment by EigenMania** [comment]
When you enter a new value into a field in the GUI, you need to leave the context of the text box in order for the changes to be reloaded / updated in the state of the GUI. So once you enter 58.8, just click into any other box, then write the config.

**Comment by ServusDei1** [comment]
Thx man you are right.
