### ISSUE TITLE
Req: 32 Bit Version for x86 handheld

### ISSUE THREAD

**Issue by Delphis1982** [danielnilsson9/bbs-fw#177]
It would be very useful, if you compile a 32 bit version as well for use in an UMPC on the road, as most of them work only with Windows 7 x86 cause of small formfactors.
I tried to compile myself, but the target framework used is only for Windows 8 or later.

I know, Win 7 is a bit old, but it is a very small OS that work flawlessly completely offline and doesn't need internet at all.
Windows 10 is too much overhead for a simple UART software and an UMPC with only 2GB RAM.
The original Bafang software even works under Windows 95.
If that's not possible anymore, then it's OK, it would be only a "nice to have".

**Comment by danielnilsson9** [comment]
.NET 6 seems to be supported on Windows 7, so it should be possible to compile a 32bit version of this. PR:s are welcome.

**Comment by Delphis1982** [comment]
I had a misconfigured Visual Studio.
Changing the Architecture worked. Thanks.
Sorry for the question.
