### ISSUE TITLE
Add a way to set up global max speed to a preselected value from a simple button pressure

### ISSUE THREAD

**Issue by Sebbaz** [danielnilsson9/bbs-fw#186]
Hello,

Is it possible to request a feature on the BBS-FW tool wich hack an existing mode (per exemple walking mode) or add one that set the global max speed to a given value ?

On the DPC18 display, there is a menu for set the max speed limit with a bit complex manipulation. The feature request is to add a way to quickly set the global speed limit to 25km/h per exemple :)

**Comment by loligeman** [comment]
what i did for this is use the sport mode to switch between 25km/h limit.

however it would be possible yes.

On Sep 22, 2023, at 1:27 AM, Sebbaz ***@***.***> wrote:

﻿

Hello,

Is it possible to request a feature on the BBS-FW tool wich hack an existing mode (per exemple walking mode) or add one that set the global max speed to a given value ?

On the DPC18 display, there is a menu for set the max speed limit with a bit complex manipulation. The feature request is to add a way to quickly set the global speed limit to 25km/h per exemple :)

**Comment by danielnilsson9** [comment]
You can config max speed per assist level.
I configure my bike with all "standard" assist levels with a max speed of 25 and all "sport" assist level with no max speed (100).
Then you can switch between the two sets using a button combination (Operation Mode Toggle in config tool).
