### ISSUE TITLE
Cant get operation mode toggle with brake sensor to work?

### ISSUE THREAD

**Issue by wressens** [danielnilsson9/bbs-fw#194]
Hello! Cant really find any info on the sport mode toggle where you hold the brakes while powering on. So when I set it to this option I cant get it to work. Tried holding both brake or one brake while turing the bike on with no success switching to sport mode. 

Will probably go back to pas+light since I realised that you cant go to normal mode other then turing the bike off.

BBS02 1.41 pretension firmware.

**Comment by wressens** [comment]
Nevermind. It worked now.

**Comment by DavesDevFails** [comment]
What was the issue? I haven't been able to get it working either... I just gave up.

**Comment by wressens** [comment]
Just held both brakes in while turning on. Maybe it started working after a restart.
