### ISSUE TITLE
Build: BATTERY_PERCENT_MAP_SW102

### ISSUE THREAD

**Issue by MrHumanRebel** [danielnilsson9/bbs-fw#202]
D:\Downloads\bbs-fw-1.4.1\src\firmware>make all TARGET_CONTROLLER=BBS02 BATTERY_PERCENT_MAP_SW102
Building bbs-fw for BBS02
sdcc -o bbsx/adc.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/adc.c
sdcc -o bbsx/eeprom.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/eeprom.c
sdcc -o bbsx/lights.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/lights.c
sdcc -o bbsx/motor.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/motor.c
sdcc -o bbsx/sensors.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/sensors.c
sdcc -o bbsx/system.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/system.c
sdcc -o bbsx/timers.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/timers.c
sdcc -o bbsx/uart.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/uart.c
sdcc -o bbsx/watchdog.rel -c -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 bbsx/watchdog.c
sdcc -o bbs-fw.ihx -I./ -Ibbsx -Ddouble=float --std-c99 -DBBS02 -mmcs51 --model-large --xram-size 1792 main.c app.rel battery.rel cfgstore.rel eventlog.rel extcom.rel throttle.rel bbsx/adc.rel bbsx/eeprom.rel bbsx/lights.rel bbsx/motor.rel bbsx/sensors.rel bbsx/system.rel bbsx/timers.rel bbsx/uart.rel bbsx/watchdog.rel
packihx: read 734 lines, wrote 1405: OK.
make: *** No rule to make target `BATTERY_PERCENT_MAP_SW102'.  Stop.

D:\Downloads\bbs-fw-1.4.1\src\firmware>

How can I specify BATTERY_PERCENT_MAP_SW102 at build? @danielnilsson9 
Thanks in advance!

**Comment by dav0000000** [comment]
Open fwconfig.h and find line 73

#define BATTERY_PERCENT_MAP						BATTERY_PERCENT_MAP_SW102
