### ISSUE TITLE
Uart protocol 

### ISSUE THREAD

**Issue by HexiDev** [danielnilsson9/bbs-fw#224]
Hi!

I was wondering if there is an layout that I can find for all the uart codes. Preferably in Hex.

Because I am trying to reverse engineer the bafang protocol and as this is a full copy I was wondering where you documented it.

**Comment by danielnilsson9** [comment]
No documentation exists. A page was started here but never finished: https://github.com/danielnilsson9/bbs-fw/wiki/Bafang-Display-Protocol

Implementation is here which should be quite easy to read:
https://github.com/danielnilsson9/bbs-fw/blob/master/src/firmware/extcom.c
