### ISSUE TITLE
Error 05 fault with throttle

### ISSUE THREAD

**Issue by st0rfrasarn** [danielnilsson9/bbs-fw#232]
Hi, i managed to flash the bbs02 firmware on a Bafang m400. (Not sure if its supported) anyway, after flashing i get ”error 05 fault with throttle”

i dont have the throttle connected, tried connecting to the blue wire in the harness coming out from the controller still same error and motor does not work

thanks

**Comment by danielnilsson9** [comment]
Try raising the lower throttle voltage option, it is set a bit too low in the default config. Raise it with 200mV and see if it works.

**Comment by danielnilsson9** [comment]
The firmware is pretty much guaranteed too not work on anything other than the supported motors. You risk destroying your controller by doing that
