### ISSUE TITLE
Voltage reading calibration

### ISSUE THREAD

**Issue by danielnilsson9** [danielnilsson9/bbs-fw#60]
Voltage reading components on PCB is of bad tolerances causing a quite significant error on some controllers.
Add possibility to calibrate from the Config Tool.

The voltage reading is used for both LVC limiting and battery percentage calculation.

**Comment by GreyXor** [comment]
My battery is at 100% rightnow, for set up the max voltage, should i trust my BMS (there is 2 volt difference between) or the value returned from controller ?

**Comment by danielnilsson9** [comment]
Since no calibration has been implemented yet it is recommended to set you max battery voltage to what the controller returns at full battery charge and the low voltage cutoff to what the controller returns when you are at your desired low voltage limit.
