### ISSUE TITLE
  Bbs02b tuned to max 3000w and 50amp controller

### ISSUE THREAD

**Issue by Bafanger** [danielnilsson9/bbs-fw#70]
Once i was using the original software i was getting 3000w peak. Now im getting max 1450w. The motor jas plenty of torque but i barely go over 30mph

**Comment by dav0000000** [comment]
3000 watts sounds expensive. Cool story though. One time I saw a fox.

**Comment by danielnilsson9** [comment]
Sounds like a bad ideá, but post boot logs from the config tool and maybe I can help you.
Also post you configuration.

See last section here:
https://github.com/danielnilsson9/bbs-fw/wiki/Configuration-Tool#event-log

**Comment by Zensaition** [comment]
> Once i was using the original software i was getting 3000w peak. Now im getting max 1450w. The motor jas plenty of torque but i barely go over 30mph

Bro post your stuff lol

**Comment by danielnilsson9** [comment]
No update, closing.
