### ISSUE TITLE
Req: Menu button as Operation Mode Toggle

### ISSUE THREAD

**Issue by CroqueMr** [danielnilsson9/bbs-fw#75]
Hi Daniel, 
Thank you so much for your incredible work. I would like to know if is it possible to add the menu button as an option to switch between road/offroad profil, this button is never used on my screen and would be the best trigger method.

**Comment by danielnilsson9** [comment]
Hi

No it's not possible the signal from that button is not sent to the motor controller so not possible to know when it is pressed.

**Comment by CroqueMr** [comment]
Thank you for your fast reply.
