### ISSUE TITLE
This needs quotes

### ISSUE THREAD

**Issue by EigenMania** [danielnilsson9/bbs-fw#85]
https://github.com/danielnilsson9/bbs-fw/blob/23cf98dacf188b936fdeb7806518f22440a65a72/src/firmware/makefile#L60

**Comment by danielnilsson9** [comment]
hmm weird, it works for me both in visual studio and from cmd line

**Comment by EigenMania** [comment]
"make clean" on cmd and "Clean Solution" on Visual Studio both fail for me without quotes. I thought first that maybe echo is trying to execute the line "Clean Finished" since clean might be a keyword, but it also fails with random words. But then maybe it's something with my system that I haven't figured out...

![image](https://user-images.githubusercontent.com/23363130/210637952-d5862ea6-31c1-41e5-9005-b22dfa7df909.png)

**Comment by danielnilsson9** [comment]
Ok no idea why that is happening for you but I will fix, not sure why I removed the quotes to be honest

**Comment by danielnilsson9** [comment]
Which make version do you have?
`make --version`

Because if I add the quotes it starts printing the quotes too which was not intended.

**Comment by EigenMania** [comment]
GNU Make 3.81, built for i386-pc-mingw32

**Comment by EigenMania** [comment]
Oh shit that's from 2006...

**Comment by danielnilsson9** [comment]
Strange, same as me, but I found a fix and removed echo and used the makefile print statement instead

**Comment by EigenMania** [comment]
Great, that worked for me too
