### ISSUE TITLE
Unused Parameter in Config: UseDisplay

### ISSUE THREAD

**Issue by EigenMania** [danielnilsson9/bbs-fw#87]
https://github.com/danielnilsson9/bbs-fw/blob/a6bf54492ba1bc0f254dcd4b17e072aa4f8d252f/src/firmware/cfgstore.h#L60

This parameter is unused in the firmware currently. Does it remain a point of development? Or can it be removed from the config. 

FYI: At least for the BBS02 and BBSHD, running without the display requires shorting P+ and PL lines on the display connector (or plugging in a programming cable): https://www.poweredride.com/info

**Comment by danielnilsson9** [comment]
Yes, that one should probably be removed, I don't remember the reason behind why it was added really. As you say, you have to power on the controller to do that so can't be done by software anyway.
