### ISSUE TITLE
Throttle Speed Control

### ISSUE THREAD

**Issue by EigenMania** [danielnilsson9/bbs-fw#92]
Original firmware allowed for a speed control mode with the throttle input. This could be a boolean option on the system tab, and throttle could be mapped to target_cadence accordingly.

**Comment by danielnilsson9** [comment]
It was intentionally skipped since I found it unusable. I'm not sure anyone actually used that, did you?

**Comment by EigenMania** [comment]
I find it quite convenient for low-speed riding (stop-and-go traffic, parking areas, and so on...) because you can modulate the speed directly with the throttle, whereas with PAS or torque throttle, the bike will accelerate to the maximum set cadence even at low current levels. I don't know exactly how / what the original firmware did for speed mode. I experimented by just setting the target cadence proportional to the throttle input, and this worked nicely.
